# Generated by Django 3.2.6 on 2021-08-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='name',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='name',
            new_name='writer',
        ),
    ]
