# Generated by Django 3.2.6 on 2021-08-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210809_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='writer',
        ),
    ]
