# Generated by Django 3.2.6 on 2021-08-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_year_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
