# Generated by Django 3.2.6 on 2021-08-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210809_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writer',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='director',
        ),
    ]
